name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest-large
    steps:
    - uses: actions/checkout@v4
    - name: Clone Ghidra    
      uses: actions/checkout@v4
      with:
        repository: NationalSecurityAgency/ghidra
        ref: Ghidra_11.0_build
        path: ghidra
    - uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-        
    - name: Deps
      run: brew install imagemagick
    - name: Build (fetchDependencies)
      run: |
        cd ghidra
        gradle -I gradle/support/fetchDependencies.gradle init
    - name: Build (buildNatives)
      run: |
        cd ghidra
        gradle buildNatives
    # - name: Build (assembleAll)
    #   run: |
    #     cd ghidra
    #     gradle assembleAll
    - name: Build (buildGhidra)
      run: |
        cd ghidra
        gradle buildGhidra
    - name: CreateGhidraApp
      run: |
        ls -lah ghidra/build/dist/
        unzip ghidra/build/dist/ghidra_11.0_*.zip -d ghidra/build/dist/
        ./CreateGhidraApp.sh ghidra/build/dist/ghidra_11.0_DEV
        zip Ghidra_11.0.zip -r Ghidra.app/
        shasum -a 256 Ghidra_11.0.zip > Ghidra_11.0.zip.sha256
    - uses: actions/upload-artifact@v4
      with:
        name: Ghidra
        path: |     
          Ghidra_11.0.zip
          Ghidra_11.0.zip.sha256                
    # - name: Release
    #   uses: softprops/action-gh-release@v1
    #   with:
    #     files: |
    #       Ghidra_11.0.zip
    #       Ghidra_11.0.zip.sha256        
    #     tag_name: v11.0