name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-13-arm64
    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        name: NationalSecurityAgency/ghidra
        ref: refs/heads/Ghidra_11.0_build
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Execute Gradle build
      run: |
        gradle -I gradle/support/fetchDependencies.gradle init
        gradle buildNatives
        gradle assembleAll
        gradle buildGhidra
    - name: Release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: "11.0"
        tag_name: ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Upload Darwin Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./bin/azblogfilter.darwin-amd64.tar.gz
        asset_name: azblogfilter.darwin-amd64.tar.gz
        asset_content_type: application/gzip