name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # runs-on: macos-latest-xlarge
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Clone Ghidra
      uses: actions/checkout@v4
      with:
        repository: NationalSecurityAgency/ghidra
        ref: Ghidra_11.0_build
        path: ghidra
    - name: Set GHIDRA_VERSION
      run: |
        echo "GHIDRA_VERSION=$(grep application.version ghidra/Ghidra/application.properties | sed "s/application.version=//")" >> $GITHUB_ENV
        echo "RUNNER_PATH=$(pwd)" >> $GITHUB_ENV
    - name: Test
      run: |
        echo $GHIDRA_VERSION
        echo $RUNNER_PATH
    - uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    # - name: Download OpenJDK 17
    #   run: |
    #     curl -L -o java.tar.gz 'https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.9%2B9/OpenJDK17U-jdk_aarch64_mac_hotspot_17.0.9_9.tar.gz'
    #     echo "823777266415347983bbd87ccd8136537242ff27e62f307b7e8521494c665f0d" java.tar.gz | shasum --algorithm 256 --check --status
    - name: Build (fetchDependencies)
      run: |
        cd ghidra
        gradle -I gradle/support/fetchDependencies.gradle init
    - name: Build (buildNatives)
      run: |
        cd ghidra
        gradle --project-dir Ghidra --init-script $RUNNER_PATH/init.gradle buildNatives_mac_arm_64
        gradle --project-dir GPL --init-script $RUNNER_PATH/init.gradle buildNatives_mac_arm_64
    # - name: Build (assembleAll)
    #   run: |
    #     cd ghidra
    #     gradle assembleAll
    - name: Build (buildGhidra)
      run: |
        cd ghidra
        gradle buildGhidra
    - name: Deps
      run: brew install imagemagick
    - name: Unzip dist/ghidra.zip
      run: |
        ls -lah ghidra/build/dist/
        unzip ghidra/build/dist/ghidra_11.0_*.zip -d ghidra/build/dist/
    - name: CreateGhidraApp
      run: |
        ls -lah
        ./CreateGhidraApp.sh ghidra/build/dist/ghidra_11.0_DEV
    # - name: Install Java
    #   run: |
    #     tar zxf java.tar.gz -C Ghidra.app/
    - name: Zip Ghidra.app
      run: |
        zip Ghidra_11.0.zip -r Ghidra.app/
        shasum -a 256 Ghidra_11.0.zip > Ghidra_11.0.zip.sha256
        cat Ghidra_11.0.zip.sha256
    - uses: actions/upload-artifact@v4
      with:
        name: Ghidra
        path: |
          Ghidra_11.0.zip
          Ghidra_11.0.zip.sha256
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          Ghidra_11.0.zip
          Ghidra_11.0.zip.sha256