name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest-xlarge
    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        repository: NationalSecurityAgency/ghidra
        ref: Ghidra_11.0_build
        path: ghidra
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Execute Gradle build
      run: |
        cd ghidra
        gradle -I gradle/support/fetchDependencies.gradle init
        gradle buildNatives
        gradle assembleAll
        gradle buildGhidra
        ../CreateGhidraApp.sh ./build/dist/ghidra_11.0_PUBLIC_*.zip
    - name: Release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: "11.0"
        tag_name: ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Upload Darwin Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/dist/Ghidra.zip
        asset_name: Ghidra.zip
        asset_content_type: application/zip